"use server";

import { Resend } from "resend";
import { z } from "zod";

const contactSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  phone: z.string().min(10, "Phone number must be at least 10 digits"),
  email: z.string().email("Invalid email address"),
  message: z.string().min(5, "Message must be at least 5 characters"),
});

export type ContactFormData = z.infer<typeof contactSchema>;

export interface ContactState {
  success: boolean;
  error: string | null;
  errors?: Record<string, string[]>;
}

export async function submitContactForm(
  prevState: ContactState,
  formData: FormData,
): Promise<ContactState> {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    console.error("Missing RESEND_API_KEY environment variable");
    return {
      success: false,
      error: "Server configuration error. Please try again later.",
      errors: undefined,
    };
  }

  const resend = new Resend(apiKey);

  // Until a domain is verified in Resend, this MUST be the sandbox sender
  // (onboarding@resend.dev), which can only deliver to your own account email.
  // Once you verify a domain, set RESEND_FROM_EMAIL to e.g.
  // "Blast Off Website <noreply@blastoffkitchenandfireservices.com>".
  const fromEmail =
    process.env.RESEND_FROM_EMAIL ||
    "Blast Off Website <onboarding@resend.dev>";

  const rawData = {
    name: formData.get("name") as string,
    phone: formData.get("phone") as string,
    email: formData.get("email") as string,
    message: formData.get("message") as string,
  };

  // Validate inputs
  const parseResult = contactSchema.safeParse(rawData);
  if (!parseResult.success) {
    const errorMap = parseResult.error.flatten().fieldErrors;
    return {
      success: false,
      error: null,
      errors: errorMap,
    };
  }

  const { name, phone, email, message } = parseResult.data;

  try {
    // 1. Send lead email to business owner (rizza@blastoffsafety.com)
    // Note: If domain is not verified, Resend requires sending from 'onboarding@resend.dev'
    const leadEmail = await resend.emails.send({
      from: fromEmail,
      to: "rizza@blastoffsafety.com",
      replyTo: email,
      subject: "New Website Quote Request - Blast Off Website",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
          <h2 style="color: #D32F2F; border-bottom: 2px solid #D32F2F; padding-bottom: 10px; margin-top: 0;">New Quote Request</h2>
          <p style="font-size: 14px; color: #555;">This lead was submitted from the contact form on <strong>blastoffkitchenandfireservices.com</strong>.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0; font-weight: bold; width: 30%;">Name:</td>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0; font-weight: bold;">Phone:</td>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0; font-weight: bold;">Email:</td>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0; font-weight: bold; vertical-align: top;">Message:</td>
              <td style="padding: 10px; border-bottom: 1px solid #f0f0f0; white-space: pre-wrap;">${message}</td>
            </tr>
          </table>
          
          <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #999;">
            This email was automatically generated by the Blast Off Kitchen Exhaust & Fire Protection Website.
          </div>
        </div>
      `,
    });

    if (leadEmail.error) {
      console.error("Resend Lead Email Error:", leadEmail.error);
      return {
        success: false,
        error:
          "Failed to send message. Please contact us directly by phone or email.",
        errors: undefined,
      };
    }

    // 2. Send auto-reply confirmation email to customer
    const autoReply = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: "We received your request",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
          <h2 style="color: #D32F2F; margin-top: 0;">Thank you for reaching out!</h2>
          <p style="font-size: 16px; line-height: 1.5; color: #333;">
            Thank you for contacting <strong>Blast Off Kitchen Exhaust Cleaning & Fire Protection</strong>.
          </p>
          <p style="font-size: 16px; line-height: 1.5; color: #333;">
            We have received your quote request and one of our specialists will get back to you shortly.
          </p>
          
          <div style="margin-top: 25px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #D32F2F; border-radius: 4px;">
            <p style="margin: 0; font-weight: bold; font-size: 14px; color: #111827;">Need Immediate Assistance?</p>
            <p style="margin: 5px 0 0 0; font-size: 14px; color: #555;">Call us directly at <strong style="color: #D32F2F;">780-918-2076</strong></p>
          </div>
          
          <hr style="border: 0; border-top: 1px solid #eeeeee; margin: 30px 0;" />
          
          <div style="font-size: 13px; color: #666;">
            <strong>Blast Off Kitchen Exhaust Cleaning & Fire Protection</strong><br />
            Unit #6, 4980 76 Street, Red Deer, AB T4P 2J8<br />
            Email: <a href="mailto:rizza@blastoffsafety.com" style="color: #D32F2F;">rizza@blastoffsafety.com</a><br />
            Web: <a href="https://blastoffkitchenandfireservices.com" style="color: #D32F2F;">blastoffkitchenandfireservices.com</a>
          </div>
        </div>
      `,
    });

    if (autoReply.error) {
      console.warn(
        "Resend Auto-Reply Email Error (not critical):",
        autoReply.error,
      );
    }

    return {
      success: true,
      error: null,
      errors: undefined,
    };
  } catch (error: unknown) {
    console.error("Contact Form Server Action Exception:", error);
    return {
      success: false,
      error:
        "An unexpected error occurred. Please try again or call us at 780-918-2076.",
      errors: undefined,
    };
  }
}
